### ISSUE TITLE
[PE-D][Tester C] Billing date is restricted to only 28 days

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#266]
![Date Range Bug.png](https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/a9c6fbc5-f3b1-4aca-9434-0539ee84cf51.png)
Billing date is restricted to only 28 days, whereas by convention, each month is 30 or 31 days, and there are companied that choose to send invoices at the last day of the month

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jinhanjinhan/ped#1

**Comment by Quasant** [comment]
Can we argue that we are the one deciding when to bill? Or prob not?

**Comment by Green-Tea-123** [comment]
The company is the one deciding when to pay their workers their salaries. The restriction of 1 to 28th is accounting for the fact that the reference is the start of the month. It is possible for us to add an enhancement that offers more formats such as taking days from the last day of the month, or the last [mon-fri] of the month.

**Comment by KengHian** [comment]
> Can we argue that we are the one deciding when to bill? Or prob not?

I think if you are want to make the argument, maybe you could make it clear in documentation. Maybe in the target user (where they handle the payment) and in the add company section (that the date is from 1 to 28th because...)

> The company is the one deciding when to pay their workers their salaries. The restriction of 1 to 28th is accounting for the fact that the reference is the start of the month. It is possible for us to add an enhancement that offers more formats such as taking days from the last day of the month, or the last [mon-fri] of the month.

The we would have to make it clear in documentation, and the end of the month part will indeed be a feature flaw to place in future enhancements.
