### ISSUE TITLE
[PE-D][Tester E] Names should allow slashes, or UG updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#292]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/6f11cf0b-77c8-457d-8761-8ff771c5e839.png)

As in title: The course website already mentioned this somewhere?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: starchypotatocode/ped#10

**Comment by Quasant** [comment]
I'm unsure of where this is coming from, I have no clue what the tester meant by `course website already mentioned this somewhere`, would be helpful to have a link.

Personally, I think it is a non-issue, since our error message already mentioned it. 
However, perhaps a possible improvement on our part would be for our UG to have one segment at the bottom detailing various input constraints (which is linked to, so as to not take up space).

**Comment by KengHian** [comment]
I think the test was referring to this, however this is not an issue with our case as our app can function without legal name of contacts. 

![image](https://github.com/user-attachments/assets/d7dc76bd-c03c-46be-bd0a-8227d90a8ecb)

**Comment by KengHian** [comment]
Reject? 
- [ ] Alek
- [ ] Ben
- [ ] Ze Wei
- [ ] Jun Boon
- [x] Keng Hian

**Comment by Quasant** [comment]
s.o. instead of s/o, there is an easy workaround.
We don't need legal name as well.
